In [3]:
# last
from llama_index.core import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    Settings,
    get_response_synthesizer,
    StorageContext,
    load_index_from_storage,
)
from llama_parse import LlamaParse
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core.node_parser import SentenceSplitter
from llama_index.llms.ollama import Ollama
from llama_index.core.retrievers import QueryFusionRetriever
from llama_index.retrievers.bm25 import BM25Retriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.evaluation import (
    RelevancyEvaluator,
    CorrectnessEvaluator,
)
import pandas as pd
import asyncio
import json
import time
import nest_asyncio
import os
from types import SimpleNamespace
from llama_index.core.llama_dataset import (
    LabelledRagDataExample,
)
import itertools

# Apply nested asyncio for notebook execution
nest_asyncio.apply()


class RAGEvaluator:
    def __init__(
        self,
        data_directory="data",
        dataset_file="./rag_dataset.json",
        index_persist_dir="./indexes",
    ):
        # Configure settings
        self._configure_settings()

        # Initialize parser and file extractor
        self.parser = LlamaParse(result_type="markdown")
        self.file_extractor = {".pdf": self.parser}

        # Set data directory and persist directory
        self.data_directory = data_directory
        self.index_persist_dir = index_persist_dir

        # Ensure index directory exists
        os.makedirs(self.index_persist_dir, exist_ok=True)

        # Load dataset
        self.rag_dataset = self._load_dataset(dataset_file)

        # Initialize evaluators
        self.relevancy_evaluator = RelevancyEvaluator()
        self.correctness_evaluator = CorrectnessEvaluator()

        # Initialize results DataFrame
        self.eval_results_df = pd.DataFrame()

        # Initialize summary results DataFrame for different parameter combinations
        self.summary_results_df = pd.DataFrame()

    def _configure_settings(self):
        """Configure global settings for embedding model and LLM"""
        Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-large-zh-v1.5")
        Settings.llm = Ollama(
            model="llama3.1:latest", request_timeout=60.0, temperature=0.3
        )

    def _load_documents(self, data_directory):
        """Load documents from the specified directory"""
        return SimpleDirectoryReader(
            data_directory, file_extractor=self.file_extractor
        ).load_data()

    def _load_dataset(self, dataset_file):
        """Load the RAG dataset from a JSON file"""
        with open(dataset_file, "r") as f:
            # Convert dictionary to object with attribute access
            return json.load(f, object_hook=lambda d: SimpleNamespace(**d))

    def _get_index_persist_path(self, chunk_size, chunk_overlap):
        """Get the directory path for persisting the index"""
        # 使用人類可讀的格式
        index_dir = f"chunk_size{chunk_size}_overlap{chunk_overlap}"
        return os.path.join(self.index_persist_dir, index_dir)

    def _create_or_load_index(self, chunk_size, chunk_overlap):
        """Create a new index or load an existing one based on chunk parameters"""
        index_persist_path = self._get_index_persist_path(chunk_size, chunk_overlap)

        if os.path.exists(index_persist_path):
            print(
                f"Loading existing index for chunk_size={chunk_size}, chunk_overlap={chunk_overlap}"
            )
            # Load existing index
            storage_context = StorageContext.from_defaults(
                persist_dir=index_persist_path
            )
            index = load_index_from_storage(storage_context)
        else:
            print(
                f"Creating new index for chunk_size={chunk_size}, chunk_overlap={chunk_overlap}"
            )
            documents = self._load_documents(self.data_directory)
            # Create text splitter with the specified chunk size and overlap
            text_splitter = SentenceSplitter(
                chunk_size=chunk_size, chunk_overlap=chunk_overlap
            )

            # Create vector index
            index = VectorStoreIndex.from_documents(
                documents, transformations=[text_splitter]
            )

            # Persist the index
            index.storage_context.persist(persist_dir=index_persist_path)

        total_num_chunks = len(index.docstore.docs)
        print(f"Loaded index with {total_num_chunks} documents")

        return index

    def _create_query_engine(self, chunk_size, chunk_overlap, top_k):
        """Create a query engine with the specified parameters"""
        # Create or load index
        index = self._create_or_load_index(chunk_size, chunk_overlap)

        # Configure retrievers with the specified top_k
        vector_retriever = index.as_retriever(similarity_top_k=top_k, verbose=True)
        bm25_retriever = BM25Retriever.from_defaults(
            docstore=index.docstore, similarity_top_k=top_k
        )

        # Create fusion retriever
        retriever = QueryFusionRetriever(
            [vector_retriever, bm25_retriever],
            similarity_top_k=top_k,
            num_queries=1,  # set to 1 to disable query generation
            mode="reciprocal_rerank",
            use_async=True,
            verbose=True,
        )

        # Create response synthesizer
        response_synthesizer = get_response_synthesizer()

        # Create and return query engine
        return RetrieverQueryEngine(
            retriever=retriever,
            response_synthesizer=response_synthesizer,
        )

    def _add_eval_row(
        self,
        response,
        dataset_example,
        relevancy_result,
        correctness_result,
        response_time,
    ):
        """Add evaluation results to the DataFrame"""
        if not response.source_nodes:
            print("No response!")
            return

        eval_row = pd.DataFrame(
            [
                {
                    "Query": dataset_example.query,
                    "Response": str(response),
                    "Reference Answer": dataset_example.reference_answer,
                    "Source": response.source_nodes[0].node.text[:1000] + "...",
                    "Relevancy Eval Result": f"{'Pass' if relevancy_result.passing else 'Fail'} \nscore: {relevancy_result.score}",
                    "Relevancy Reasoning": relevancy_result.feedback,
                    "Correctness Eval Result": f"{'Pass' if correctness_result.passing else 'Fail'} \n\nscore: {correctness_result.score}",
                    "Correctness Reasoning": correctness_result.feedback,
                    "Response Time": f"{response_time:.4f}",
                }
            ]
        )

        self.eval_results_df = pd.concat(
            [self.eval_results_df, eval_row], ignore_index=True
        )

    async def _evaluate_engine(
        self, query_engine, dataset_examples: LabelledRagDataExample
    ):
        """Evaluate the query engine on the given examples"""
        # # Limit to first 3 examples for testing
        # dataset_examples = dataset_examples[:3]

        # Initialize tracking variables
        relevancy_total_correct = 0
        correctness_total_correct = 0
        correctness_total_score = 0
        total_response_time = 0

        # Process each example
        for dataset_example in dataset_examples:
            start_time = time.time()
            response = query_engine.query(dataset_example.query)
            response_time = time.time() - start_time

            # Evaluate relevancy and correctness
            relevancy_result = self.relevancy_evaluator.evaluate_response(
                query=dataset_example.query, response=response
            )
            correctness_result = self.correctness_evaluator.evaluate_response(
                query=dataset_example.query,
                response=response,
                reference=dataset_example.reference_answer,
            )

            # Add results to DataFrame
            self._add_eval_row(
                response,
                dataset_example,
                relevancy_result,
                correctness_result,
                response_time,
            )

            # Update totals
            total_response_time += response_time
            if relevancy_result.passing:
                relevancy_total_correct += 1
            if correctness_result.passing:
                correctness_total_correct += 1
                correctness_total_score += correctness_result.score

        return (
            relevancy_total_correct,
            correctness_total_correct,
            correctness_total_score,
            len(dataset_examples),
            total_response_time,
        )

    def evaluate_with_params(self, chunk_size, chunk_overlap, top_k):
        """Run evaluation with the specified parameters"""
        print(
            f"Parameters: chunk_size={chunk_size}, chunk_overlap={chunk_overlap}, top_k={top_k}"
        )

        # Reset results DataFrame
        self.eval_results_df = pd.DataFrame()

        # Create query engine with the specified parameters
        query_engine = self._create_query_engine(chunk_size, chunk_overlap, top_k)

        # Run evaluation
        (
            relevancy_total_correct,
            correctness_total_correct,
            correctness_total_score,
            total_questions,
            total_response_time,
        ) = asyncio.run(self._evaluate_engine(query_engine, self.rag_dataset.examples))

        # Display results
        styled_df = self.eval_results_df.style.set_properties(
            **{"white-space": "pre-wrap"},
        )

        display(styled_df)

        # Calculate scores
        relevancy_score = relevancy_total_correct / total_questions
        correctness_score = correctness_total_score / total_questions
        avg_response_time = total_response_time / total_questions

        # Display summary
        print(
            f"Total Relevancy correct: {relevancy_total_correct} out of {total_questions}, "
            f"score: {relevancy_score}"
        )
        print(
            f"Total Correctness correct: {correctness_total_correct} out of {total_questions}, "
            f"score: {correctness_score}"
        )
        print(f"Average response time: {avg_response_time:.4f} seconds")
        print("===============================================")

        # Add result to summary DataFrame
        self._add_summary_row(
            chunk_size,
            chunk_overlap,
            top_k,
            relevancy_score,
            correctness_score,
            avg_response_time,
        )

        return {
            "relevancy_score": relevancy_score,
            "correctness_score": correctness_score,
            "avg_response_time": avg_response_time,
        }

    def _add_summary_row(
        self,
        chunk_size,
        chunk_overlap,
        top_k,
        relevancy_score,
        correctness_score,
        avg_response_time,
    ):
        """Add a summary row to the summary results DataFrame"""
        summary_row = pd.DataFrame(
            [
                {
                    "Chunk Size": chunk_size,
                    "Chunk Overlap": chunk_overlap,
                    "Top K": top_k,
                    "Relevancy Score": f"{relevancy_score:.4f}",
                    "Correctness Score": f"{correctness_score:.4f}",
                    "Avg Response Time": f"{avg_response_time:.4f}",
                }
            ]
        )

        self.summary_results_df = pd.concat(
            [self.summary_results_df, summary_row], ignore_index=True
        )
        self.summary_results_df.to_csv(
            "summary_results_second_half_last_2.csv", index=False
        )

    def run_evaluations(self, chunk_sizes, overlaps, top_ks):
        """Run evaluations for multiple parameter combinations"""
        # Reset summary results DataFrame
        # self.summary_results_df = pd.DataFrame()

        # Generate all parameter combinations
        param_combinations = list(itertools.product(chunk_sizes, overlaps, top_ks))
        total_combinations = len(param_combinations)

        print(f"Running evaluations for {total_combinations} parameter combinations...")

        results = {}
        for i, (chunk_size, overlap, top_k) in enumerate(param_combinations):
            print(f"\nEvaluation {i+1}/{total_combinations}")
            # Convert overlap from percentage to absolute value
            chunk_overlap = int(chunk_size * overlap)
            results[(chunk_size, overlap, top_k)] = self.evaluate_with_params(
                chunk_size, chunk_overlap, top_k
            )

        # Display summary table
        self._display_summary_table()

        return results

    def _display_summary_table(self):
        """Display a summary table of all parameter combinations"""
        print("\n--- Summary of All Parameter Combinations ---")

        # Sort the summary results by scores
        sorted_df = self.summary_results_df.sort_values(
            by=["Relevancy Score", "Correctness Score"], ascending=False
        )

        display(sorted_df)

        # Find the best parameter combination
        best_row = sorted_df.iloc[0]
        print(f"\nBest Parameter Combination:")
        print(f"Chunk Size: {best_row['Chunk Size']}")
        print(f"Chunk Overlap: {best_row['Chunk Overlap']}")
        print(f"Top K: {best_row['Top K']}")
        print(f"Relevancy Score: {best_row['Relevancy Score']}")
        print(f"Correctness Score: {best_row['Correctness Score']}")
        print(f"Avg Response Time: {best_row['Avg Response Time']} seconds")

In [ ]:
[128, 192, 256, 384, 512, 768, 1024, 1536, 2048]

In [4]:
evaluator = RAGEvaluator()

# Define parameter ranges to test
# (512,51,8)~
# (512,25,3)~(512,102,12)
top_ks = [5,7,10]


chunk_sizes = [768]
overlaps = [0.15, 0.2]
results = evaluator.run_evaluations(chunk_sizes, overlaps, top_ks)

chunk_sizes = [1024, 1536, 2048]
overlaps = [0.05, 0.1, 0.15, 0.2]
results = evaluator.run_evaluations(chunk_sizes, overlaps, top_ks)

# Define parameter ranges to test
chunk_sizes = [128, 192, 256, 384]
overlaps = [0.05]
results = evaluator.run_evaluations(chunk_sizes, overlaps, top_ks)

Running evaluations for 6 parameter combinations...

Evaluation 1/6
Parameters: chunk_size=768, chunk_overlap=115, top_k=5
Creating new index for chunk_size=768, chunk_overlap=115
Started parsing the file under job_id 4fe689a7-c111-4cca-a73d-ae0d7b62d0c8
Started parsing the file under job_id 02f06c3f-5d47-4a94-857e-5aa4a96e0ee1
Started parsing the file under job_id f19f06a2-8499-4124-8aa8-dc0e46b0910e
Started parsing the file under job_id b2fb7bb8-b0d2-4505-8464-eeae85ece101
Started parsing the file under job_id 81aa5063-5ec3-4d3e-b7ed-1ee10f66e5de
Started parsing the file under job_id 78cf7a23-6817-48bc-840f-c44a13325fdc
Loaded index with 25 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 29 out of 30, score: 3.9
Average response time: 2.7209 seconds
===============================================

Evaluation 2/6
Parameters: chunk_size=768, chunk_overlap=115, top_k=7
Loading existing index for chunk_size=768, chunk_overlap=115
Loaded index with 25 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 27 out of 30, score: 3.6
Average response time: 5.3221 seconds
===============================================

Evaluation 3/6
Parameters: chunk_size=768, chunk_overlap=115, top_k=10
Loading existing index for chunk_size=768, chunk_overlap=115
Loaded index with 25 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 26 out of 30, score: 3.466666666666667
Average response time: 8.1202 seconds
===============================================

Evaluation 4/6
Parameters: chunk_size=768, chunk_overlap=153, top_k=5
Creating new index for chunk_size=768, chunk_overlap=153
Started parsing the file under job_id 012f2dd8-96cb-481a-acbb-32e24b214ee0
Error while parsing the file '<bytes/buffer>': Server disconnected without sending a response.
Started parsing the file under job_id a40cfef0-2770-4615-bb5f-bd409cf24dcc
Error while parsing the file '<bytes/buffer>': Failed to parse the file: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

Started parsing the file under job_id 16d0b080-41f6-459f-8fe4-91806eaf22dd
Started parsing the file under job_id e038fa1b-3c20-481a-88b4-6f302cf2fca0
Started parsing the file under job_id 90dd6fc3-1319-41da-a6a8-80eb907957d2
Loaded index with 19 documents

Total Relevancy correct: 25 out of 30, score: 0.8333333333333334
Total Correctness correct: 26 out of 30, score: 3.466666666666667
Average response time: 2.9967 seconds
===============================================

Evaluation 5/6
Parameters: chunk_size=768, chunk_overlap=153, top_k=7
Loading existing index for chunk_size=768, chunk_overlap=153
Loaded index with 19 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 22 out of 30, score: 2.933333333333333
Average response time: 5.8271 seconds
===============================================

Evaluation 6/6
Parameters: chunk_size=768, chunk_overlap=153, top_k=10
Loading existing index for chunk_size=768, chunk_overlap=153
Loaded index with 19 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 22 out of 30, score: 2.933333333333333
Average response time: 5.9118 seconds
===============================================

--- Summary of All Parameter Combinations ---

,Chunk Size,Chunk Overlap,Top K,Relevancy Score,Correctness Score,Avg Response Time
2,768,115,10,0.9333,3.4667,8.1202
5,768,153,10,0.9333,2.9333,5.9118
0,768,115,5,0.9000,3.9000,2.7209
1,768,115,7,0.9000,3.6000,5.3221
4,768,153,7,0.9000,2.9333,5.8271
3,768,153,5,0.8333,3.4667,2.9967

Best Parameter Combination:
Chunk Size: 768
Chunk Overlap: 115
Top K: 10
Relevancy Score: 0.9333
Correctness Score: 3.4667
Avg Response Time: 8.1202 seconds
Running evaluations for 36 parameter combinations...

Evaluation 1/36
Parameters: chunk_size=1024, chunk_overlap=51, top_k=5
Creating new index for chunk_size=1024, chunk_overlap=51
Started parsing the file under job_id d2f9cf47-73ef-40e2-9ace-13bd59ed764e
Started parsing the file under job_id 3353d83d-ab24-4e32-8a9c-4b61764bc718
Started parsing the file under job_id 977c6f34-bf53-48e1-9240-892c16a41bf9
Started parsing the file under job_id 1eb47e29-483f-4baa-b613-9fadaf789bfd
Started parsing the file under job_id 224586ae-e6b0-4486-b28b-b0050061c084
Started parsing the file under job_id d7b7f8ec-4dd9-45a7-9edd-c4f79b7ca2dc
Loaded index with 22 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 29 out of 30, score: 3.8666666666666667
Average response time: 1.9859 seconds
===============================================

Evaluation 2/36
Parameters: chunk_size=1024, chunk_overlap=51, top_k=7
Loading existing index for chunk_size=1024, chunk_overlap=51
Loaded index with 22 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 28 out of 30, score: 3.7333333333333334
Average response time: 3.8292 seconds
===============================================

Evaluation 3/36
Parameters: chunk_size=1024, chunk_overlap=51, top_k=10
Loading existing index for chunk_size=1024, chunk_overlap=51
Loaded index with 22 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 24 out of 30, score: 3.2
Average response time: 6.5200 seconds
===============================================

Evaluation 4/36
Parameters: chunk_size=1024, chunk_overlap=102, top_k=5
Loading existing index for chunk_size=1024, chunk_overlap=102
Loaded index with 22 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 29 out of 30, score: 3.8666666666666667
Average response time: 2.0597 seconds
===============================================

Evaluation 5/36
Parameters: chunk_size=1024, chunk_overlap=102, top_k=7
Loading existing index for chunk_size=1024, chunk_overlap=102
Loaded index with 22 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 25 out of 30, score: 3.3333333333333335
Average response time: 4.5555 seconds
===============================================

Evaluation 6/36
Parameters: chunk_size=1024, chunk_overlap=102, top_k=10
Loading existing index for chunk_size=1024, chunk_overlap=102
Loaded index with 22 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 23 out of 30, score: 3.066666666666667
Average response time: 6.0719 seconds
===============================================

Evaluation 7/36
Parameters: chunk_size=1024, chunk_overlap=153, top_k=5
Loading existing index for chunk_size=1024, chunk_overlap=153
Loaded index with 22 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 29 out of 30, score: 3.933333333333333
Average response time: 1.9838 seconds
===============================================

Evaluation 8/36
Parameters: chunk_size=1024, chunk_overlap=153, top_k=7
Loading existing index for chunk_size=1024, chunk_overlap=153
Loaded index with 22 documents

Total Relevancy correct: 25 out of 30, score: 0.8333333333333334
Total Correctness correct: 23 out of 30, score: 3.066666666666667
Average response time: 4.1684 seconds
===============================================

Evaluation 9/36
Parameters: chunk_size=1024, chunk_overlap=153, top_k=10
Loading existing index for chunk_size=1024, chunk_overlap=153
Loaded index with 22 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 25 out of 30, score: 3.3333333333333335
Average response time: 7.3471 seconds
===============================================

Evaluation 10/36
Parameters: chunk_size=1024, chunk_overlap=204, top_k=5
Creating new index for chunk_size=1024, chunk_overlap=204
Started parsing the file under job_id c23ac73d-828b-4e1a-a56c-db1f51b21297
Started parsing the file under job_id ae658f82-b107-4c79-bc22-a9f0a67e95a1
Started parsing the file under job_id 551fa32e-406a-4d95-ad96-ffd11faee061
Started parsing the file under job_id fd3497cd-5beb-4bfb-aaa9-948d1d2e9318
Started parsing the file under job_id 89735675-bec9-4b1c-adef-84a3cfa2aac8
Started parsing the file under job_id 852f87bb-922d-4e1a-ac6f-0eca1231c0b7
Loaded index with 22 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 29 out of 30, score: 3.8666666666666667
Average response time: 2.2829 seconds
===============================================

Evaluation 11/36
Parameters: chunk_size=1024, chunk_overlap=204, top_k=7
Loading existing index for chunk_size=1024, chunk_overlap=204
Loaded index with 22 documents

Total Relevancy correct: 25 out of 30, score: 0.8333333333333334
Total Correctness correct: 20 out of 30, score: 2.7
Average response time: 4.7697 seconds
===============================================

Evaluation 12/36
Parameters: chunk_size=1024, chunk_overlap=204, top_k=10
Loading existing index for chunk_size=1024, chunk_overlap=204
Loaded index with 22 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 22 out of 30, score: 2.933333333333333
Average response time: 8.8992 seconds
===============================================

Evaluation 13/36
Parameters: chunk_size=1536, chunk_overlap=76, top_k=5
Creating new index for chunk_size=1536, chunk_overlap=76
Started parsing the file under job_id 8a621e2f-5ef4-4f34-9ecb-3bd6bc9fc38a
Started parsing the file under job_id 04357652-e54d-4ea2-85c8-1ec06745994f
Started parsing the file under job_id 317aeeee-9adc-4e70-8ae2-23f4afa7c94e
Started parsing the file under job_id a81b849c-60b4-4341-914a-64ca12109506
Started parsing the file under job_id df91dc75-09b0-4d8b-aa43-475fc542406f
Started parsing the file under job_id 784159dd-3df6-43e2-9b71-79f2b92b6046
Loaded index with 16 documents

Total Relevancy correct: 30 out of 30, score: 1.0
Total Correctness correct: 25 out of 30, score: 3.3666666666666667
Average response time: 4.3494 seconds
===============================================

Evaluation 14/36
Parameters: chunk_size=1536, chunk_overlap=76, top_k=7
Loading existing index for chunk_size=1536, chunk_overlap=76
Loaded index with 16 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 25 out of 30, score: 3.3333333333333335
Average response time: 8.1517 seconds
===============================================

Evaluation 15/36
Parameters: chunk_size=1536, chunk_overlap=76, top_k=10
Loading existing index for chunk_size=1536, chunk_overlap=76
Loaded index with 16 documents

Total Relevancy correct: 25 out of 30, score: 0.8333333333333334
Total Correctness correct: 22 out of 30, score: 2.933333333333333
Average response time: 9.4241 seconds
===============================================

Evaluation 16/36
Parameters: chunk_size=1536, chunk_overlap=153, top_k=5
Creating new index for chunk_size=1536, chunk_overlap=153
Started parsing the file under job_id 073e484c-cb03-41ea-80fd-a818f7532500
Started parsing the file under job_id 9e40d3a9-8ff8-4629-9808-3acd947f66f5
Started parsing the file under job_id d9a7fb93-5c0b-41ae-829d-c2195897050c
Started parsing the file under job_id a987efd9-2603-4a2d-9fec-282581ae7c59
Started parsing the file under job_id 3c36036d-1307-494c-8944-536b460fb881
Started parsing the file under job_id 8c4dfd79-ecde-448c-a5ca-4da1b290b2bb
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 26 out of 30, score: 3.533333333333333
Average response time: 6.3540 seconds
===============================================

Evaluation 17/36
Parameters: chunk_size=1536, chunk_overlap=153, top_k=7
Loading existing index for chunk_size=1536, chunk_overlap=153
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 27 out of 30, score: 3.6
Average response time: 8.9962 seconds
===============================================

Evaluation 18/36
Parameters: chunk_size=1536, chunk_overlap=153, top_k=10
Loading existing index for chunk_size=1536, chunk_overlap=153
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 22 out of 30, score: 2.933333333333333
Average response time: 12.7139 seconds
===============================================

Evaluation 19/36
Parameters: chunk_size=1536, chunk_overlap=230, top_k=5
Creating new index for chunk_size=1536, chunk_overlap=230
Started parsing the file under job_id c5def78d-d945-4d4e-9f85-b3b18171d97b
Started parsing the file under job_id 4862d51d-2681-4703-9cbb-fbd585e99e6e
Started parsing the file under job_id 358fd152-351b-4924-ad84-b4cf37b39879
Started parsing the file under job_id 0ed04c73-8fe6-4a05-ae7e-d543545c4096
Started parsing the file under job_id d04b79b3-baf7-473d-ad89-71fbd64950ee
Started parsing the file under job_id b5f4e5dd-7105-49ae-998f-84e186b43b6b
Loaded index with 16 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 23 out of 30, score: 3.066666666666667
Average response time: 7.0938 seconds
===============================================

Evaluation 20/36
Parameters: chunk_size=1536, chunk_overlap=230, top_k=7
Loading existing index for chunk_size=1536, chunk_overlap=230
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 26 out of 30, score: 3.466666666666667
Average response time: 9.7418 seconds
===============================================

Evaluation 21/36
Parameters: chunk_size=1536, chunk_overlap=230, top_k=10
Loading existing index for chunk_size=1536, chunk_overlap=230
Loaded index with 16 documents

Total Relevancy correct: 30 out of 30, score: 1.0
Total Correctness correct: 21 out of 30, score: 2.8
Average response time: 10.0441 seconds
===============================================

Evaluation 22/36
Parameters: chunk_size=1536, chunk_overlap=307, top_k=5
Creating new index for chunk_size=1536, chunk_overlap=307
Started parsing the file under job_id 26d2f414-da1d-4d75-8d1e-4b0cc2f69d70
Started parsing the file under job_id a706a511-787c-4e78-8e1c-c837324caf09
Started parsing the file under job_id e78868e4-5204-4612-bec4-99f25318dcd5
Started parsing the file under job_id 6c9168a1-c0a4-4cc7-8122-89c5d64ab4ae
Started parsing the file under job_id 19a2671f-8eca-449d-8303-372733381cb3
Started parsing the file under job_id db435f93-3202-4967-bb3b-fed6bd236b5f
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 29 out of 30, score: 3.8666666666666667
Average response time: 6.6885 seconds
===============================================

Evaluation 23/36
Parameters: chunk_size=1536, chunk_overlap=307, top_k=7
Loading existing index for chunk_size=1536, chunk_overlap=307
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 23 out of 30, score: 3.066666666666667
Average response time: 8.7264 seconds
===============================================

Evaluation 24/36
Parameters: chunk_size=1536, chunk_overlap=307, top_k=10
Loading existing index for chunk_size=1536, chunk_overlap=307
Loaded index with 16 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 21 out of 30, score: 2.8
Average response time: 9.8823 seconds
===============================================

Evaluation 25/36
Parameters: chunk_size=2048, chunk_overlap=102, top_k=5
Creating new index for chunk_size=2048, chunk_overlap=102
Started parsing the file under job_id ab909009-08d8-486f-af06-a7ed2042c8cb
Started parsing the file under job_id 34849eaa-41b1-4ee8-abc2-38686e612598
Started parsing the file under job_id 8a76233e-8e18-4fed-982a-2d7ae4a9f565
Started parsing the file under job_id e0cc8b0c-1035-4a5a-9fb9-cc25d5298dcc
Started parsing the file under job_id 4b466859-1311-4aa6-a4e4-4ab2bcef7fff
Started parsing the file under job_id 9469731e-b2ad-4220-8c01-f7990402efd0
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 26 out of 30, score: 3.466666666666667
Average response time: 6.3125 seconds
===============================================

Evaluation 26/36
Parameters: chunk_size=2048, chunk_overlap=102, top_k=7
Loading existing index for chunk_size=2048, chunk_overlap=102
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 24 out of 30, score: 3.2
Average response time: 7.1246 seconds
===============================================

Evaluation 27/36
Parameters: chunk_size=2048, chunk_overlap=102, top_k=10
Loading existing index for chunk_size=2048, chunk_overlap=102
Loaded index with 16 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 25 out of 30, score: 3.3333333333333335
Average response time: 9.1744 seconds
===============================================

Evaluation 28/36
Parameters: chunk_size=2048, chunk_overlap=204, top_k=5
Loading existing index for chunk_size=2048, chunk_overlap=204
Loaded index with 16 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 25 out of 30, score: 3.3666666666666667
Average response time: 3.5675 seconds
===============================================

Evaluation 29/36
Parameters: chunk_size=2048, chunk_overlap=204, top_k=7
Loading existing index for chunk_size=2048, chunk_overlap=204
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 24 out of 30, score: 3.2
Average response time: 5.7909 seconds
===============================================

Evaluation 30/36
Parameters: chunk_size=2048, chunk_overlap=204, top_k=10
Loading existing index for chunk_size=2048, chunk_overlap=204
Loaded index with 16 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 21 out of 30, score: 2.8
Average response time: 8.8981 seconds
===============================================

Evaluation 31/36
Parameters: chunk_size=2048, chunk_overlap=307, top_k=5
Loading existing index for chunk_size=2048, chunk_overlap=307
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 27 out of 30, score: 3.6
Average response time: 3.8734 seconds
===============================================

Evaluation 32/36
Parameters: chunk_size=2048, chunk_overlap=307, top_k=7
Loading existing index for chunk_size=2048, chunk_overlap=307
Loaded index with 16 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 26 out of 30, score: 3.466666666666667
Average response time: 6.2200 seconds
===============================================

Evaluation 33/36
Parameters: chunk_size=2048, chunk_overlap=307, top_k=10
Loading existing index for chunk_size=2048, chunk_overlap=307
Loaded index with 16 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 26 out of 30, score: 3.466666666666667
Average response time: 9.0427 seconds
===============================================

Evaluation 34/36
Parameters: chunk_size=2048, chunk_overlap=409, top_k=5
Loading existing index for chunk_size=2048, chunk_overlap=409
Loaded index with 16 documents

Total Relevancy correct: 30 out of 30, score: 1.0
Total Correctness correct: 24 out of 30, score: 3.2
Average response time: 3.7722 seconds
===============================================

Evaluation 35/36
Parameters: chunk_size=2048, chunk_overlap=409, top_k=7
Loading existing index for chunk_size=2048, chunk_overlap=409
Loaded index with 16 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 23 out of 30, score: 3.066666666666667
Average response time: 6.0276 seconds
===============================================

Evaluation 36/36
Parameters: chunk_size=2048, chunk_overlap=409, top_k=10
Loading existing index for chunk_size=2048, chunk_overlap=409
Loaded index with 16 documents

Total Relevancy correct: 30 out of 30, score: 1.0
Total Correctness correct: 21 out of 30, score: 2.8
Average response time: 11.9728 seconds
===============================================

--- Summary of All Parameter Combinations ---

,Chunk Size,Chunk Overlap,Top K,Relevancy Score,Correctness Score,Avg Response Time
18,1536,76,5,1.0000,3.3667,4.3494
39,2048,409,5,1.0000,3.2000,3.7722
26,1536,230,10,1.0000,2.8000,10.0441
41,2048,409,10,1.0000,2.8000,11.9728
12,1024,153,5,0.9667,3.9333,1.9838
6,1024,51,5,0.9667,3.8667,1.9859
27,1536,307,5,0.9667,3.8667,6.6885
7,1024,51,7,0.9667,3.7333,3.8292
22,1536,153,7,0.9667,3.6000,8.9962
36,2048,307,5,0.9667,3.6000,3.8734
21,1536,153,5,0.9667,3.5333,6.3540
25,1536,230,7,0.9667,3.4667,9.7418
30,2048,102,5,0.9667,3.4667,6.3125
38,2048,307,10,0.9667,3.4667,9.0427
14,1024,153,10,0.9667,3.3333,7.3471
31,2048,102,7,0.9667,3.2000,7.1246
34,2048,204,7,0.9667,3.2000,5.7909
28,1536,307,7,0.9667,3.0667,8.7264
17,1024,204,10,0.9667,2.9333,8.8992
23,1536,153,10,0.9667,2.9333,12.7139
9,1024,102,5,0.9333,3.8667,2.0597
2,768,115,10,0.9333,3.4667,8.1202
33,2048,204,5,0.9333,3.3667,3.5675
32,2048,102,10,0.9333,3.3333,9.1744
11,1024,102,10,0.9333,3.0667,6.0719
24,1536,230,5,0.9333,3.0667,7.0938
5,768,153,10,0.9333,2.9333,5.9118
29,1536,307,10,0.9333,2.8000,9.8823
35,2048,204,10,0.9333,2.8000,8.8981
0,768,115,5,0.9000,3.9000,2.7209
15,1024,204,5,0.9000,3.8667,2.2829
1,768,115,7,0.9000,3.6000,5.3221
37,2048,307,7,0.9000,3.4667,6.2200
10,1024,102,7,0.9000,3.3333,4.5555
19,1536,76,7,0.9000,3.3333,8.1517
8,1024,51,10,0.9000,3.2000,6.5200
40,2048,409,7,0.9000,3.0667,6.0276
4,768,153,7,0.9000,2.9333,5.8271
3,768,153,5,0.8333,3.4667,2.9967
13,1024,153,7,0.8333,3.0667,4.1684
20,1536,76,10,0.8333,2.9333,9.4241
16,1024,204,7,0.8333,2.7000,4.7697

Best Parameter Combination:
Chunk Size: 1536
Chunk Overlap: 76
Top K: 5
Relevancy Score: 1.0000
Correctness Score: 3.3667
Avg Response Time: 4.3494 seconds
Running evaluations for 12 parameter combinations...

Evaluation 1/12
Parameters: chunk_size=128, chunk_overlap=6, top_k=5
Creating new index for chunk_size=128, chunk_overlap=6
Started parsing the file under job_id 1da2ee50-c6aa-47d9-aba4-9bd596b58238
Started parsing the file under job_id b5107bd3-9089-4de0-bc0e-1e02515e7c7f
Started parsing the file under job_id 1da542d3-211d-4a11-bc01-39a12d2e9a82
Started parsing the file under job_id e5d57980-f3bb-48c5-bd05-0319c8d81091
Started parsing the file under job_id 4a08c71c-5ff9-4803-b0ca-90618822adc3
Started parsing the file under job_id e350cb48-7bc6-4eb1-9444-3f8b10649017
Loaded index with 191 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 28 out of 30, score: 3.8
Average response time: 1.3226 seconds
===============================================

Evaluation 2/12
Parameters: chunk_size=128, chunk_overlap=6, top_k=7
Loading existing index for chunk_size=128, chunk_overlap=6
Loaded index with 191 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 28 out of 30, score: 3.8
Average response time: 1.3326 seconds
===============================================

Evaluation 3/12
Parameters: chunk_size=128, chunk_overlap=6, top_k=10
Loading existing index for chunk_size=128, chunk_overlap=6
Loaded index with 191 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 28 out of 30, score: 3.7333333333333334
Average response time: 1.6568 seconds
===============================================

Evaluation 4/12
Parameters: chunk_size=192, chunk_overlap=9, top_k=5
Creating new index for chunk_size=192, chunk_overlap=9
Started parsing the file under job_id 6bfb44be-7c1b-45f5-b326-ed42431f75ef
Started parsing the file under job_id dffda11d-94ec-43ba-9fd4-f245843b2ae4
Started parsing the file under job_id 3625f2f4-9082-44d9-a34a-246c414abb80
Started parsing the file under job_id 41bccd64-6c33-4b41-b1e5-b42cf36f1e52
Started parsing the file under job_id 440e1109-59c8-4856-9ace-991c97b08b5c
Started parsing the file under job_id 2f8a49f4-253b-4afa-97f7-43a32670722a
Loaded index with 109 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 27 out of 30, score: 3.6333333333333333
Average response time: 1.4500 seconds
===============================================

Evaluation 5/12
Parameters: chunk_size=192, chunk_overlap=9, top_k=7
Loading existing index for chunk_size=192, chunk_overlap=9
Loaded index with 109 documents

Total Relevancy correct: 29 out of 30, score: 0.9666666666666667
Total Correctness correct: 28 out of 30, score: 3.8
Average response time: 1.8975 seconds
===============================================

Evaluation 6/12
Parameters: chunk_size=192, chunk_overlap=9, top_k=10
Loading existing index for chunk_size=192, chunk_overlap=9
Loaded index with 109 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 29 out of 30, score: 3.933333333333333
Average response time: 2.1450 seconds
===============================================

Evaluation 7/12
Parameters: chunk_size=256, chunk_overlap=12, top_k=5
Creating new index for chunk_size=256, chunk_overlap=12
Started parsing the file under job_id 9458d755-26f3-40d9-a44e-0aa9c15f81d6
Started parsing the file under job_id 2fc0eefa-7d1e-4a23-a921-f55be7327672
Started parsing the file under job_id 69b9541c-ece1-447d-b083-409baedcd1bf
Started parsing the file under job_id a3c4a8fb-fbdc-459e-b076-ba623f23a0e1
Started parsing the file under job_id e21a69ee-ba96-4c15-9e39-471156a3432c
Started parsing the file under job_id 3f8c0905-0f52-45c4-a530-1d3ea4b18fee
Loaded index with 79 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 27 out of 30, score: 3.6
Average response time: 1.9227 seconds
===============================================

Evaluation 8/12
Parameters: chunk_size=256, chunk_overlap=12, top_k=7
Loading existing index for chunk_size=256, chunk_overlap=12
Loaded index with 79 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 30 out of 30, score: 4.0
Average response time: 2.1223 seconds
===============================================

Evaluation 9/12
Parameters: chunk_size=256, chunk_overlap=12, top_k=10
Loading existing index for chunk_size=256, chunk_overlap=12
Loaded index with 79 documents

Total Relevancy correct: 27 out of 30, score: 0.9
Total Correctness correct: 28 out of 30, score: 3.7666666666666666
Average response time: 2.3185 seconds
===============================================

Evaluation 10/12
Parameters: chunk_size=384, chunk_overlap=19, top_k=5
Creating new index for chunk_size=384, chunk_overlap=19
Started parsing the file under job_id 6413a8ae-d6a5-483d-b283-5d1ef32f77ce
Started parsing the file under job_id cdc6e33a-72fd-437d-bc2c-b3c2ccf934c4
Started parsing the file under job_id aad85cef-0ce6-43d6-bb73-e25d6b88bb17
Started parsing the file under job_id eaea6209-ccba-42a6-8ed9-7170ee88304e
Started parsing the file under job_id a175827a-5f3b-4863-a26c-fc45a2608d76
Started parsing the file under job_id cebb2833-d328-476f-8db2-ddba94288ba7
Loaded index with 51 documents

Total Relevancy correct: 30 out of 30, score: 1.0
Total Correctness correct: 29 out of 30, score: 3.8666666666666667
Average response time: 1.8271 seconds
===============================================

Evaluation 11/12
Parameters: chunk_size=384, chunk_overlap=19, top_k=7
Loading existing index for chunk_size=384, chunk_overlap=19
Loaded index with 51 documents

Total Relevancy correct: 28 out of 30, score: 0.9333333333333333
Total Correctness correct: 30 out of 30, score: 4.0
Average response time: 1.5654 seconds
===============================================

Evaluation 12/12
Parameters: chunk_size=384, chunk_overlap=19, top_k=10
Loading existing index for chunk_size=384, chunk_overlap=19
Loaded index with 51 documents

Total Relevancy correct: 30 out of 30, score: 1.0
Total Correctness correct: 29 out of 30, score: 3.9
Average response time: 1.5728 seconds
===============================================

--- Summary of All Parameter Combinations ---

,Chunk Size,Chunk Overlap,Top K,Relevancy Score,Correctness Score,Avg Response Time
53,384,19,10,1.0000,3.9000,1.5728
51,384,19,5,1.0000,3.8667,1.8271
18,1536,76,5,1.0000,3.3667,4.3494
39,2048,409,5,1.0000,3.2000,3.7722
26,1536,230,10,1.0000,2.8000,10.0441
41,2048,409,10,1.0000,2.8000,11.9728
12,1024,153,5,0.9667,3.9333,1.9838
6,1024,51,5,0.9667,3.8667,1.9859
27,1536,307,5,0.9667,3.8667,6.6885
46,192,9,7,0.9667,3.8000,1.8975
7,1024,51,7,0.9667,3.7333,3.8292
44,128,6,10,0.9667,3.7333,1.6568
22,1536,153,7,0.9667,3.6000,8.9962
36,2048,307,5,0.9667,3.6000,3.8734
21,1536,153,5,0.9667,3.5333,6.3540
25,1536,230,7,0.9667,3.4667,9.7418
30,2048,102,5,0.9667,3.4667,6.3125
38,2048,307,10,0.9667,3.4667,9.0427
14,1024,153,10,0.9667,3.3333,7.3471
31,2048,102,7,0.9667,3.2000,7.1246
34,2048,204,7,0.9667,3.2000,5.7909
28,1536,307,7,0.9667,3.0667,8.7264
17,1024,204,10,0.9667,2.9333,8.8992
23,1536,153,10,0.9667,2.9333,12.7139
52,384,19,7,0.9333,4.0000,1.5654
9,1024,102,5,0.9333,3.8667,2.0597
42,128,6,5,0.9333,3.8000,1.3226
43,128,6,7,0.9333,3.8000,1.3326
45,192,9,5,0.9333,3.6333,1.4500
48,256,12,5,0.9333,3.6000,1.9227
2,768,115,10,0.9333,3.4667,8.1202
33,2048,204,5,0.9333,3.3667,3.5675
32,2048,102,10,0.9333,3.3333,9.1744
11,1024,102,10,0.9333,3.0667,6.0719
24,1536,230,5,0.9333,3.0667,7.0938
5,768,153,10,0.9333,2.9333,5.9118
29,1536,307,10,0.9333,2.8000,9.8823
35,2048,204,10,0.9333,2.8000,8.8981
49,256,12,7,0.9000,4.0000,2.1223
47,192,9,10,0.9000,3.9333,2.1450
0,768,115,5,0.9000,3.9000,2.7209
15,1024,204,5,0.9000,3.8667,2.2829
50,256,12,10,0.9000,3.7667,2.3185
1,768,115,7,0.9000,3.6000,5.3221
37,2048,307,7,0.9000,3.4667,6.2200
10,1024,102,7,0.9000,3.3333,4.5555
19,1536,76,7,0.9000,3.3333,8.1517
8,1024,51,10,0.9000,3.2000,6.5200
40,2048,409,7,0.9000,3.0667,6.0276
4,768,153,7,0.9000,2.9333,5.8271
3,768,153,5,0.8333,3.4667,2.9967
13,1024,153,7,0.8333,3.0667,4.1684
20,1536,76,10,0.8333,2.9333,9.4241
16,1024,204,7,0.8333,2.7000,4.7697

Best Parameter Combination:
Chunk Size: 384
Chunk Overlap: 19
Top K: 10
Relevancy Score: 1.0000
Correctness Score: 3.9000
Avg Response Time: 1.5728 seconds